### ISSUE TITLE
ECCV5:Learning and Matching Multi-View Descriptors for Registration of Point Clouds

### ISSUE THREAD

**Issue by elliottzheng** [PaoPaoPointCloud/ArticlesToBedistributed#12]
编辑：
应上交时间:
记得在发布issue的时候打上label，刚发布时，为`待申领`，申领人回复issue即为申领,并将issue分配(assigness)给自己，申领后设置标签为`待设置上交时间`，并将任务给编辑，设置完上交时间后为`待上交`，上交时，回复issue，设置label为`已上交待发布`，发布后就关闭issue。

**Comment by xuershuai123** [comment]
Application

**Comment by elliottzheng** [comment]
@xuershuai123  
上交时间：10.18

**Comment by elliottzheng** [comment]
有啥问题及时联系哈

**Comment by xuershuai123** [comment]
好的，

**Comment by xuershuai123** [comment]
你好，我申请的论文已提交，关于论文里特征配准部分有点读不懂，不能很好的表达作者的方法，这边是不是再分派一人专门写一下特征匹配这部分，请见谅

**Comment by elliottzheng** [comment]
我找时间看下，再安排下一步，没事

--------------原始邮件--------------
发件人："xuershuai123 "<notifications@github.com>;
发送时间：2018年10月15日(星期一) 下午5:05
收件人："PaoPaoPointCloud/ArticlesToBedistributed" <ArticlesToBedistributed@noreply.github.com>;
抄送："Eliott Zheng "<zheng@yinglin.top>;"Author "<author@noreply.github.com>;
主题：Re: [PaoPaoPointCloud/ArticlesToBedistributed] ECCV5:Learning andMatching Multi-View Descriptors for Registration of Point Clouds (#12)
-----------------------------------

 
你好，我申请的论文已提交，关于论文里特征配准部分有点读不懂，不能很好的表达作者的方法，这边是不是再分派一人专门写一下特征匹配这部分，请见谅
