### ISSUE TITLE
ECCV19﻿: 3DMV: Joint 3D-Multi-View Prediction for 3D Semantic Scene Segmentation﻿

### ISSUE THREAD

**Issue by elliottzheng** [PaoPaoPointCloud/ArticlesToBedistributed#5]
编辑：云峰
应上交时间：10.9

**Comment by elliottzheng** [comment]
【泡泡点云时空】3DMV:联合三维多视图预测的三维语义场景分割(ECCV-19)
作者：Angela Dai, Matthias Nieβner
我们提出了一种利用三维多视点联合预测网络进行室内RGB-D扫描的三维语义场景分割的新方法—3DMV。与现有的使用几何或RGB数据作为此任务输入的方法相比，我们将这两种数据模式组合在端到端的联合网络架构中。我们不是简单地将颜色数据投影到体网格中并且只以三维的方式操作{这将导致细节不足}，而是首先从相关的RGB图像中提取特征映射。然后使用可微后向投影层将这些特征映射到3D网络的体素特征网格中。由于我们的目标是可能具有许多帧的3D扫描场景，因此我们使用多视图池化方法来处理数量不同的RGB输入视图。通过我们的联合2D-3D网络架构学习到的RGB和几何特征得到的结果显著优于现有基准。例如，我们将ScanNet 3D分割基准测试的最终结果精度从现有的体素架构的52.8%提高到了75%。

**Comment by elliottzheng** [comment]
@Elly524 请音频组组织配音工作。

**Comment by icameling** [comment]
已发布
