### ISSUE TITLE
CVPR5﻿: A Minimalist Approach to Type-Agnostic Detection of Quadrics in Point Clouds﻿

### ISSUE THREAD

**Issue by elliottzheng** [PaoPaoPointCloud/ArticlesToBedistributed#8]
编辑：木木
应上交时间:10.17
记得在发布issue的时候打上label，刚发布时，为`待申领`，申领后为`待设置上交时间`，并将任务分配给编辑，设置完上交时间后为`待上交`，上交后为`已上交待发布`，发布后就关闭issue。

**Comment by MuMuJun97** [comment]
@elliottzheng  test the information

**Comment by elliottzheng** [comment]
@MuMuJun97 不知道你会收到邮件吗

**Comment by MuMuJun97** [comment]
@elliottzheng  已经上传到秀米，请查收，
------>【泡泡点云空间】点云中未知类型二次曲面的一种极简检测方法（CVPR-2018）
------>  [【文章下载链接】](https://arxiv.org/abs/1803.07191)

**Comment by elliottzheng** [comment]
收到

**Comment by MuMuJun97** [comment]
get

**Comment by elliottzheng** [comment]
【泡泡点云时空】点云中未知类型二次曲面的一种极简检测方法（CVPR-2018）
文章标题：A Minimalist Approach to Type-Agnostic Detection of Quadrics in Point Clouds
本文提出了一种无分割，自动且有效的方法来检测点云中的一般几何二次曲面，在这种情况下，杂波和遮挡是不可避免的。我们的日常世界由人造物体主导，这些物体使用3D基元（例如平面，圆锥体，球体，圆柱体等）设计而来。这些对象在工业环境中也无所不在。这使得通过基元抽象3D场景成为可能，从而将这些几何形状定位为感知和高级3D场景理解的组成部分。与最先进的技术相比，定制的算法可以分别处理每种基元类型，我们提出将所有类型封装在单个稳健的检测过程中。我们的方法的核心是一个封闭形式的3D二次曲面拟合，在原始空间和对偶空间中运行，并且至少需要4个定向点。围绕这一点，我们设计了一种新颖的局部零空间投票策略，将4点情况减少到3。投票与著名的RANSAC相结合，使我们的算法比传统算法快几个数量级。这是第一种能够在困难的场景中执行通用的交叉型多对象基元检测的方法。合成和真实数据集上的实验结果证明了我们方法的有效性。

**Comment by icameling** [comment]
已发布
